name: pangyangjourney
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  #Utility Packages
  device_preview: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  #Icon
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.1
  flutter_map_location_marker: ^9.0.0
  flutter_map_marker_popup: ^7.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

