// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpCaroAj9z77TG2o2hwPycsRvT1WIOto',
    appId: '1:599826163278:web:f1d7d11ba8c205b564851f',
    messagingSenderId: '599826163278',
    projectId: 'pangyangjourney',
    authDomain: 'pangyangjourney.firebaseapp.com',
    storageBucket: 'pangyangjourney.appspot.com',
    measurementId: 'G-1E1H6W7YPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1dGQPZreChpg1-vFiVukMkBRgk0gX4Ks',
    appId: '1:599826163278:android:f6819962cb00e04864851f',
    messagingSenderId: '599826163278',
    projectId: 'pangyangjourney',
    storageBucket: 'pangyangjourney.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsog2ypPHwqIWTCwiu1vdNS3tkw2KULCE',
    appId: '1:599826163278:ios:2b3f5c17cf6e79c264851f',
    messagingSenderId: '599826163278',
    projectId: 'pangyangjourney',
    storageBucket: 'pangyangjourney.appspot.com',
    iosBundleId: 'com.example.pangyangjourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsog2ypPHwqIWTCwiu1vdNS3tkw2KULCE',
    appId: '1:599826163278:ios:2b3f5c17cf6e79c264851f',
    messagingSenderId: '599826163278',
    projectId: 'pangyangjourney',
    storageBucket: 'pangyangjourney.appspot.com',
    iosBundleId: 'com.example.pangyangjourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDpCaroAj9z77TG2o2hwPycsRvT1WIOto',
    appId: '1:599826163278:web:c7b6f10f5e60793564851f',
    messagingSenderId: '599826163278',
    projectId: 'pangyangjourney',
    authDomain: 'pangyangjourney.firebaseapp.com',
    storageBucket: 'pangyangjourney.appspot.com',
    measurementId: 'G-CQM058YBGN',
  );

}